# -*- coding: utf-8 -*-
"""Assignment_No_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQ9OYUZzp9vlswta315FH_kOoe-1GXRU

# Problem Statement :-

    Data Visualization I
        1. Use the inbuilt dataset 'titanic'. The dataset contains 891 rows and contains information about the
            passengers who boarded the unfortunate Titanic ship. Use the Seaborn library to see if we can find
            any patterns in the data.
        2. Write a code to check how the price of the ticket (column name: 'fare') for each passenger is
            distributed by plotting a histogram.

## Importing Libraries and dataset
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

df = sns.load_dataset('titanic')
df.head()

df.info()

df.describe()

"""## Handling Null Values"""

df.isna().sum()

df.drop(['deck'], axis = 1, inplace = True)

df['embarked'].value_counts()

df['embarked'].fillna(df['embarked'].mode()[0], inplace = True)
df['embarked'].value_counts()

df['embark_town'].value_counts()

df['embark_town'].fillna(df['embark_town'].mode()[0], inplace = True)
df['embark_town'].value_counts()

df['age'].fillna(df['age'].mean(), inplace = True)

df.isna().sum()

"""# Taks1:

# Distributional Plots

## The Dist Plot
"""

sns.distplot(df['fare'], kde=False, bins=10)
# You can clearly see that for more than 700 passengers, the ticket price is between 0 and 50

"""## The Joint Plot """

sns.jointplot(x='age', y='fare', data=df)
# You can see that there is no correlation observed between age and the fares.

"""## The Rug Plot"""

sns.rugplot(df['fare'])
# most of the instances for the fares have values between 0 and 100.

"""# Categorical Plots

## The Bar Plot
"""

sns.barplot(x='sex', y='age', data=df)
#The average age of male passengers is around 30 while the average age of female passengers is just less than 30.

sns.barplot(x='embarked', y='age', data=df)

"""## The Count Plot"""

sns.countplot(x='sex', hue = 'survived', data=df)
# Displays the count of the categories in a specific column

sns.countplot(x = 'class', hue = 'survived', data = df)

"""## The Box Plot """

sns.boxplot(x='sex', y='age', data=df)
# male=> 1st quartile:(5-22) 2nd quartile:(23-30) 3rd quartile:(31-35) 4th quartile:(36-52)

df.corr()

plt.figure(figsize=(15,10))
ax = sns.heatmap(df.corr())

sns.displot(df, x = 'age', kde = True)
# most of the passengers age is between 30 to 33

sns.displot(df, x = 'embarked')
# most of the passengers are from SouthHampton

"""# Task2:"""

sns.barplot(data = df, y = 'fare', x = 'who')

sns.barplot(data = df, y = 'fare', x = 'sex')

sns.barplot(data = df, y = 'fare', x = 'alone')

sns.barplot(data = df, y = 'fare', x = 'embarked')

sns.barplot(data = df, y = 'fare', x = 'pclass')