# -*- coding: utf-8 -*-
"""Assignment_No_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mm93312NMKhf0vvgg9SMy4I0Z0EDI1p3

# Problem Statement :-

    Data Visualization II
        1. Use the inbuilt dataset 'titanic' as used in the above problem. Plot a box plot for distribution of age
            with respect to each gender along with the information about whether they survived or not. (Column
            names: 'sex' and 'age')
        2. Write observations on the inference from the above statistics.

## Importing Libraries and dataset
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = sns.load_dataset('titanic')
df.head()

df.info()

df.describe()

"""## Handling Null Values"""

df.isna().sum()

df.drop(['deck'], axis = 1, inplace = True)

df['embarked'].fillna(df['embarked'].mode()[0], inplace = True)

df['embark_town'].fillna(df['embark_town'].mode()[0], inplace = True)

df['age'].fillna(df['age'].mean(), inplace = True)

df.isna().sum()

"""# Task1:"""

sns.boxplot(x = 'sex', y = 'age', data = df)

sns.boxplot(x='sex', y='age', data=df, hue="survived")

"""# Task2:"""

# 1. Now in addition to the information about the age of each gender, we can also see the distribution of the passengers who survived.
# 2. We can see that among the male passengers, on average more younger people survived as compared to the older ones.
# 3. We can see that among the female passengers, on average more older people survived as compared to the older ones.